package com.sandy.fda.models.enums;

public enum TokenType {
    KEYWORD,
    USERHOOK,
    INBUILDFUNCTION,
    FUNCTION,
    OPEN_BRACKET,
    CLOSE_BRACKET,
    COMMA,
    REP_VARIABLE,
    STRING_OR_CHAR_LITERAL,
    NUMBER_LITERAL,
    SV_VARIABLE,
    FV_VARIABLE,
    COMPARISON_OPERATOR,
    ARITHMETIC_OPERATOR,
    AND_OPERATOR,
    OR_OPERATOR,
    VALID_EXPRESSION,
    VALID_FUNCTION
}
