java.port=52000
java.host=127.0.0.1
c24.output.dir={c24-output}
fi.<env>={fi-url}
c24.<env>.host={c24-host}
c24.<env>.port={c24-port}
c24.<env>.username={c24-username}
c24.<env>.password={c24-password}
c24.<env>.bankId={c24-bankId}
c24.<env>.bePath={c24-appPath}
c24.<env>.fePath={c24-warPath}