# Assigned automatically if not provided
java.port={java-port}

# Do not change; this must remain localhost
java.host=127.0.0.1

# c24.output.dir: Directory where C24-generated files are created
c24.output.dir={c24-output}

# FI request endpoint
fi.<env>={fi-url}

# c24.<env>.host: Host for the C24 deployment feature
c24.<env>.host={c24-host}

# c24.<env>.port: Port for the C24 deployment feature
c24.<env>.port={c24-port}

# c24.<env>.username: Username for C24 deployment
c24.<env>.username={c24-username}

# c24.<env>.password: Password for C24 deployment
c24.<env>.password={c24-password}

# c24.<env>.bankId: Bank ID used for C24 deployment
c24.<env>.bankId={c24-bankId}

# c24.<env>.bePath: Backend application path for C24 deployment
c24.<env>.bePath={c24-appPath}

# c24.<env>.fePath: Frontend WAR path for C24 deployment
c24.<env>.fePath={c24-warPath}